# Generated by Django 4.2.4 on 2023-08-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_semi_finished_number',
            field=models.IntegerField(default=0, verbose_name='半成品数量'),
        ),
    ]
