# Generated by Django 4.2.4 on 2023-08-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_semi_finished_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMaterialGetNormal',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('product_storage_id', models.IntegerField(default=0, verbose_name='产品入库id')),
                ('product_name', models.CharField(default=0, max_length=32, verbose_name='产品名')),
                ('product_number', models.FloatField(default=0, verbose_name='产品数量')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGetNormal',
            fields=[
                ('product_storage_id', models.AutoField(primary_key=True, serialize=False, verbose_name='产品入库id')),
                ('apply_user_id', models.IntegerField(default=3, verbose_name='申请人id')),
                ('create_time', models.CharField(default='未填写', max_length=32, verbose_name='申请创建时间')),
                ('production_order_id', models.CharField(max_length=32, verbose_name='生产指令单id')),
                ('quality_confirm', models.IntegerField(default=0, verbose_name='品控确认')),
                ('product_storage_img', models.CharField(max_length=32, verbose_name='产品入库单')),
                ('warehousing_confirm', models.IntegerField(default=0, verbose_name='仓库确认')),
                ('quality_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='品控确认时间')),
                ('warehousing_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='仓库确认时间')),
            ],
        ),
    ]
