# Generated by Django 4.2.4 on 2023-08-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_linkmaterialgetnormal_materialgetnormal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkMaterialGetNormal',
            new_name='LinkProductStorageNormal',
        ),
        migrations.RenameModel(
            old_name='MaterialGetNormal',
            new_name='ProductStorageNormal',
        ),
    ]
