# Generated by Django 4.2.4 on 2023-08-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_linkproductshipmentnormal_productshipmentnormal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productshipmentnormal',
            old_name='product_storage_img',
            new_name='product_shipment_img',
        ),
    ]
