# Generated by Django 4.2.4 on 2023-08-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_storage_img_productshipmentnormal_product_shipment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshipmentnormal',
            name='warehousing_confirm',
            field=models.IntegerField(default=2, verbose_name='仓库确认'),
        ),
        migrations.AlterField(
            model_name='productstoragenormal',
            name='warehousing_confirm',
            field=models.IntegerField(default=2, verbose_name='仓库确认'),
        ),
    ]
