# Generated by Django 4.2.4 on 2023-08-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productshipmentnormal_warehousing_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_number',
            field=models.CharField(default='无', max_length=10, verbose_name='货架号'),
        ),
    ]
