# Generated by Django 4.2.4 on 2023-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='材料id')),
                ('material_name', models.CharField(max_length=32, verbose_name='材料名')),
                ('material_weight', models.IntegerField(verbose_name='原料重量')),
                ('recycle_material_weight', models.IntegerField(verbose_name='水口料重量')),
            ],
        ),
    ]
