# Generated by Django 4.2.4 on 2023-08-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='材料名'),
        ),
    ]
