# Generated by Django 4.2.4 on 2023-08-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_rawmaterial_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='材料id'),
        ),
    ]
