# Generated by Django 4.2.4 on 2023-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_materialpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMaterialPurchase',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('material_purchase_id', models.IntegerField(verbose_name='原料采购单据id')),
                ('material_name', models.CharField(max_length=32, unique=True, verbose_name='材料名')),
                ('material_purchase_weight', models.FloatField(verbose_name='原料购买重量')),
            ],
        ),
        migrations.AddField(
            model_name='materialpurchase',
            name='quality_confirm_time',
            field=models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='品控确认时间'),
        ),
        migrations.AddField(
            model_name='materialpurchase',
            name='warehousing_confirm_time',
            field=models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='仓库确认时间'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='create_time',
            field=models.CharField(max_length=32, verbose_name='申请创建时间'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='delivery_note_img',
            field=models.CharField(max_length=32, verbose_name='送货单'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='warehousing_entry_img',
            field=models.CharField(max_length=32, verbose_name='入库单'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_weight',
            field=models.FloatField(verbose_name='原料重量'),
        ),
    ]
