# Generated by Django 4.2.4 on 2023-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_linkmaterialpurchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmaterialpurchase',
            name='material_name',
            field=models.CharField(max_length=32, verbose_name='材料名'),
        ),
    ]
