# Generated by Django 4.2.4 on 2023-08-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_linkmaterialpurchase_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmaterialpurchase',
            name='material_supplier',
            field=models.CharField(default='供应商', max_length=16, verbose_name='材料供应商'),
        ),
    ]
