# Generated by Django 4.2.4 on 2023-08-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_linkmaterialpurchase_material_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmaterialpurchase',
            name='material_from',
            field=models.CharField(default='采购', max_length=8, verbose_name='材料来源'),
        ),
    ]
