# Generated by Django 4.2.4 on 2023-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_materialpurchase_warehousing_entry_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMaterialBack',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('material_back_id', models.IntegerField(verbose_name='原料采购单据id')),
                ('material_name', models.CharField(max_length=32, verbose_name='材料名')),
                ('material_back_kind', models.IntegerField(verbose_name='材料退库种类')),
                ('material_back_weight', models.FloatField(verbose_name='原料购买重量')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBack',
            fields=[
                ('material_back_id', models.AutoField(primary_key=True, serialize=False, verbose_name='材料退库单id')),
                ('apply_user_id', models.IntegerField(verbose_name='申请人id')),
                ('create_time', models.CharField(max_length=32, verbose_name='申请创建时间')),
                ('back_warehouse_img', models.CharField(max_length=32, verbose_name='退库单')),
                ('factory_manager_confirm', models.IntegerField(default=0, verbose_name='厂长确认')),
                ('warehousing_confirm', models.IntegerField(default=0, verbose_name='仓库确认')),
                ('factory_manager_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='厂长确认时间')),
                ('warehousing_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='仓库确认时间')),
            ],
        ),
    ]
