# Generated by Django 4.2.4 on 2023-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_linkmaterialback_materialback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmaterialback',
            name='material_back_id',
            field=models.IntegerField(verbose_name='原料退库单据id'),
        ),
    ]
