# Generated by Django 4.2.4 on 2023-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_linkmaterialback_material_back_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmaterialback',
            name='back_remark',
            field=models.CharField(default='无备注', max_length=50, verbose_name='备注'),
        ),
    ]
