# Generated by Django 4.2.4 on 2023-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_linkmaterialback_back_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMaterialOutFactory',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('material_out_factory_id', models.IntegerField(verbose_name='材料出厂单id')),
                ('material_name', models.CharField(max_length=32, verbose_name='材料名')),
                ('material_kind', models.IntegerField(verbose_name='材料种类')),
                ('material_weight', models.FloatField(verbose_name='材料出厂重量')),
                ('remark', models.CharField(max_length=10, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOutFactory',
            fields=[
                ('material_out_factory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='材料出厂单id')),
                ('apply_user_id', models.IntegerField(verbose_name='申请人id')),
                ('create_time', models.CharField(max_length=32, verbose_name='申请创建时间')),
                ('material_out_factory_img', models.CharField(max_length=32, verbose_name='材料出厂单')),
                ('deputy_manager_confirm', models.IntegerField(default=0, verbose_name='副总确认')),
                ('general_manager_confirm', models.IntegerField(default=0, verbose_name='总经理确认')),
                ('warehousing_confirm', models.IntegerField(default=0, verbose_name='仓库确认')),
                ('deputy_manager_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='副总经理确认时间')),
                ('general_manager_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='总经理确认时间')),
                ('warehousing_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='仓库确认时间')),
            ],
        ),
    ]
