# Generated by Django 4.2.4 on 2023-08-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_linkmaterialoutfactory_materialoutfactory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialSupplier',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('material_name', models.CharField(max_length=32, unique=True, verbose_name='材料名')),
                ('material_supplier', models.CharField(max_length=32, verbose_name='供应商名称')),
                ('material_weight', models.FloatField(verbose_name='原料重量')),
            ],
        ),
        migrations.CreateModel(
            name='RecycleMaterialSupplier',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('material_name', models.CharField(max_length=32, unique=True, verbose_name='材料名')),
                ('material_supplier', models.CharField(max_length=32, verbose_name='供应商名称')),
                ('material_weight', models.FloatField(verbose_name='水口料重量')),
            ],
        ),
    ]
