# Generated by Django 4.2.4 on 2023-08-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_rawmaterialsupplier_recyclematerialsupplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawMaterialSupplier',
        ),
        migrations.DeleteModel(
            name='RecycleMaterialSupplier',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material_product_supplier',
            field=models.CharField(default='生产厂商', max_length=32, verbose_name='生产厂商名称'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material_supplier',
            field=models.CharField(default='供应商', max_length=32, verbose_name='供应商名称'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('material_id', 'material_name', 'material_supplier', 'material_product_supplier')},
        ),
    ]
