# Generated by Django 4.2.4 on 2023-08-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_delete_rawmaterialsupplier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('material_name', 'material_supplier', 'material_product_supplier')},
        ),
    ]
