# Generated by Django 4.2.4 on 2023-08-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_rawmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(default='6414型', max_length=32, unique=True, verbose_name='材料型号'),
        ),
    ]
