# Generated by Django 4.2.4 on 2023-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_alter_rawmaterial_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_name',
            field=models.CharField(max_length=32, verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(default='6414型', max_length=32, verbose_name='材料型号'),
        ),
    ]
