# Generated by Django 4.2.4 on 2023-08-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_rawmaterial_material_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('material_name', 'material_type', 'material_supplier', 'material_product_supplier')},
        ),
    ]
