# Generated by Django 4.2.4 on 2023-08-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_alter_rawmaterial_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmaterialback',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='linkmaterialoutfactory',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='linkmaterialpurchase',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='linkmaterialpurchase',
            name='material_supplier',
        ),
        migrations.AddField(
            model_name='linkmaterialback',
            name='material_id',
            field=models.IntegerField(default=0, verbose_name='材料id'),
        ),
        migrations.AddField(
            model_name='linkmaterialoutfactory',
            name='material_id',
            field=models.IntegerField(default=0, verbose_name='材料id'),
        ),
        migrations.AddField(
            model_name='linkmaterialpurchase',
            name='material_id',
            field=models.IntegerField(default=0, verbose_name='材料id'),
        ),
        migrations.AddField(
            model_name='materialback',
            name='production_order_status',
            field=models.IntegerField(default=1, verbose_name='指令单状态'),
        ),
        migrations.AlterField(
            model_name='linkmaterialback',
            name='material_back_weight',
            field=models.FloatField(verbose_name='材料退库重量'),
        ),
    ]
