# Generated by Django 4.2.4 on 2023-08-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_remove_linkmaterialback_material_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='recycle_material_weight',
            field=models.FloatField(verbose_name='水口料重量'),
        ),
    ]
