# Generated by Django 4.2.4 on 2023-08-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_alter_rawmaterial_recycle_material_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_weight',
            field=models.FloatField(default=0, verbose_name='原料重量'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='recycle_material_weight',
            field=models.FloatField(default=0, verbose_name='水口料重量'),
        ),
    ]
