# Generated by Django 4.2.4 on 2023-08-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_alter_rawmaterial_material_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMaterialGetNormal',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('material_id', models.IntegerField(default=0, verbose_name='材料id')),
                ('material_kind', models.IntegerField(verbose_name='材料退库种类')),
                ('material_weight', models.FloatField(verbose_name='材料退库重量')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGetNormal',
            fields=[
                ('material_get_id', models.AutoField(primary_key=True, serialize=False, verbose_name='材料领取id')),
                ('production_order_id', models.CharField(max_length=32, verbose_name='生产指令单id')),
                ('factory_manager_confirm', models.IntegerField(default=0, verbose_name='厂长确认')),
                ('material_get_img', models.CharField(max_length=32, verbose_name='材料领取单')),
                ('warehousing_confirm', models.IntegerField(default=0, verbose_name='仓库确认')),
                ('factory_manager_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='厂长确认时间')),
                ('warehousing_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='仓库确认时间')),
            ],
        ),
    ]
