# Generated by Django 4.2.4 on 2023-08-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_linkmaterialgetnormal_materialgetnormal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmaterialgetnormal',
            name='material_kind',
        ),
    ]
