# Generated by Django 4.2.4 on 2023-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_alter_rawmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='remark',
            field=models.CharField(default='无备注', max_length=50, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='shelf_number',
            field=models.CharField(default='无', max_length=10, verbose_name='货架编号'),
        ),
    ]
