# Generated by Django 4.2.4 on 2023-08-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_rawmaterial_remark_rawmaterial_shelf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialback',
            name='warehousing_confirm',
            field=models.IntegerField(default=2, verbose_name='仓库确认'),
        ),
        migrations.AlterField(
            model_name='materialgetnormal',
            name='warehousing_confirm',
            field=models.IntegerField(default=2, verbose_name='仓库确认'),
        ),
        migrations.AlterField(
            model_name='materialoutfactory',
            name='general_manager_confirm',
            field=models.IntegerField(default=2, verbose_name='总经理确认'),
        ),
        migrations.AlterField(
            model_name='materialoutfactory',
            name='warehousing_confirm',
            field=models.IntegerField(default=2, verbose_name='仓库确认'),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='warehousing_confirm',
            field=models.IntegerField(default=2, verbose_name='仓库确认'),
        ),
    ]
