# Generated by Django 3.0 on 2023-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('true_name', models.CharField(max_length=6, verbose_name='真实姓名')),
                ('role_id', models.IntegerField(verbose_name='身份码')),
            ],
        ),
    ]
