# Generated by Django 4.2.4 on 2023-08-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkProductionOrderByMaterial',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('production_order_id', models.IntegerField(verbose_name='原料退库单据id')),
                ('material_name', models.CharField(max_length=32, verbose_name='材料名')),
                ('material_order_kind', models.IntegerField(verbose_name='材料种类')),
                ('material_order_weight', models.FloatField(verbose_name='材料重量')),
            ],
        ),
        migrations.CreateModel(
            name='LinkProductionOrderByProduct',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('production_order_id', models.IntegerField(verbose_name='生产指令单据id')),
                ('product_name', models.CharField(max_length=32, verbose_name='产品名')),
                ('product_number', models.IntegerField(verbose_name='订单产品数量')),
                ('product_weight', models.FloatField(verbose_name='产品净重')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('production_order_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='生产指令单编号')),
                ('apply_user_id', models.IntegerField(verbose_name='申请人id')),
                ('create_time', models.CharField(max_length=32, verbose_name='申请创建时间')),
                ('mould_name', models.CharField(max_length=64, verbose_name='磨具编号')),
                ('molding_cycle', models.CharField(max_length=32, verbose_name='成型周期')),
                ('delivery_note_img', models.CharField(max_length=32, verbose_name='内部生产指令单')),
                ('quality_confirm', models.IntegerField(default=0, verbose_name='品控确认')),
                ('deputy_general_manager_confirm', models.IntegerField(default=0, verbose_name='副总确认')),
                ('quality_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='品控确认时间')),
                ('deputy_general_manager_confirm_time', models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='副总确认时间')),
            ],
        ),
    ]
