# Generated by Django 4.2.4 on 2023-08-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='production_control_upload_time',
            field=models.CharField(default='yyyy-mm-dd hh:mm:ss', max_length=32, verbose_name='生管上传单据时间'),
        ),
    ]
