# Generated by Django 4.2.4 on 2023-08-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_productionorder_production_control_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='production_control_upload',
            field=models.IntegerField(default=0, verbose_name='生管上传'),
        ),
    ]
