# Generated by Django 4.2.4 on 2023-08-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_productionorder_production_control_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkproductionorderbymaterial',
            name='material_used_weight',
            field=models.FloatField(default=0, verbose_name='已领取材料重量'),
        ),
        migrations.AddField(
            model_name='linkproductionorderbyproduct',
            name='product_received_number',
            field=models.IntegerField(default=0, verbose_name='产品已入库数量'),
        ),
    ]
