# Generated by Django 4.2.4 on 2023-08-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_linkproductionorderbymaterial_material_used_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkproductionorderbyproduct',
            name='product_shipped_number',
            field=models.IntegerField(default=0, verbose_name='产品已出货数量'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='custom',
            field=models.CharField(default='无', max_length=10, verbose_name='客户'),
        ),
    ]
