# Generated by Django 4.2.4 on 2023-08-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_linkproductionorderbyproduct_product_shipped_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkproductionorderbymaterial',
            name='production_order_id',
            field=models.CharField(max_length=32, verbose_name='生产指令单据id'),
        ),
        migrations.AlterField(
            model_name='linkproductionorderbyproduct',
            name='production_order_id',
            field=models.CharField(max_length=32, verbose_name='生产指令单据id'),
        ),
    ]
