# Generated by Django 4.2.4 on 2023-08-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_linkproductionorderbymaterial_production_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorder',
            old_name='delivery_note_img',
            new_name='production_order_img',
        ),
    ]
