# Generated by Django 4.2.4 on 2023-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_delivery_note_img_productionorder_production_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='custom_deadline',
            field=models.CharField(default='9999-99-99', max_length=12, verbose_name='客户交期'),
        ),
    ]
