# Generated by Django 4.2.4 on 2023-08-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_linkproductionorderbymaterial_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='production_order_status',
            field=models.IntegerField(default=1, verbose_name='指令单状态'),
        ),
    ]
